import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MAX_SONGS_PER_REQUEST = 10; // YouTube API quota limit protection

interface Song {
  artist: string;
  track_name: string;
}

async function searchVideo(accessToken: string, query: string): Promise<string | null> {
  const searchUrl = new URL('https://www.googleapis.com/youtube/v3/search');
  searchUrl.searchParams.set('part', 'snippet');
  searchUrl.searchParams.set('q', query);
  searchUrl.searchParams.set('type', 'video');
  searchUrl.searchParams.set('videoCategoryId', '10'); // Music category
  searchUrl.searchParams.set('maxResults', '1');

  const response = await fetch(searchUrl.toString(), {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  const data = await response.json();
  
  if (data.error) {
    console.error('YouTube search error:', data.error);
    return null;
  }

  return data.items?.[0]?.id?.videoId || null;
}

async function createPlaylist(accessToken: string, title: string, description: string): Promise<string> {
  const response = await fetch('https://www.googleapis.com/youtube/v3/playlists?part=snippet,status', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      snippet: { title, description },
      status: { privacyStatus: 'private' },
    }),
  });

  const data = await response.json();
  
  if (data.error) {
    throw new Error(data.error.message || 'Failed to create playlist');
  }

  return data.id;
}

async function addVideoToPlaylist(accessToken: string, playlistId: string, videoId: string): Promise<boolean> {
  const response = await fetch('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      snippet: {
        playlistId,
        resourceId: { kind: 'youtube#video', videoId },
      },
    }),
  });

  const data = await response.json();
  return !data.error;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { accessToken, songs, playlistName } = await req.json();

    if (!accessToken) {
      throw new Error('Access token required');
    }

    if (!songs || !Array.isArray(songs) || songs.length === 0) {
      throw new Error('Songs array required');
    }

    // Enforce 10-song limit for API quota protection
    const limitedSongs: Song[] = songs.slice(0, MAX_SONGS_PER_REQUEST);
    const wasLimited = songs.length > MAX_SONGS_PER_REQUEST;

    console.log(`Processing ${limitedSongs.length} songs (original: ${songs.length})`);

    // Create the playlist
    const title = playlistName || 'My AI Generated Playlist';
    const description = `Generated by Playlist AI • ${new Date().toLocaleDateString()}`;
    const playlistId = await createPlaylist(accessToken, title, description);

    console.log('Created playlist:', playlistId);

    // Search and add each song
    const results: { song: Song; videoId: string | null; added: boolean }[] = [];

    for (const song of limitedSongs) {
      const query = `${song.artist} ${song.track_name} official`;
      const videoId = await searchVideo(accessToken, query);
      
      let added = false;
      if (videoId) {
        added = await addVideoToPlaylist(accessToken, playlistId, videoId);
      }

      results.push({ song, videoId, added });
      
      // Small delay to avoid rate limiting
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    const addedCount = results.filter(r => r.added).length;

    return new Response(JSON.stringify({
      success: true,
      playlistId,
      playlistUrl: `https://www.youtube.com/playlist?list=${playlistId}`,
      songsProcessed: limitedSongs.length,
      songsAdded: addedCount,
      wasLimited,
      originalCount: songs.length,
      results,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error: unknown) {
    console.error('YouTube playlist creation error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
